AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  out-tonight

  Template for out-tonight

Globals:
  Function:
    Timeout: 3

Resources:
  OutTonightFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: out_tonight/
      Handler: out_tonight.out_tonight_handler
      Runtime: python3.8
      Policies: AmazonDynamoDBFullAccess
      Events:
        OutTonight:
          Type: Api
          Properties:
            Path: /out-tonight
            Method: get
  
  OutTonightTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: out_or_not
        Type: String

Outputs:
  OutTonightApi:
    Description: "API Gateway endpoint URL for Prod stage for out-tonight function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/out-tonight/"
  OutTonightFunction:
    Description: "out-tonight Lambda Function ARN"
    Value: !GetAtt OutTonightFunction.Arn
  OutTonightFunctionIamRole:
    Description: "Implicit IAM Role created for out-tonight function"
    Value: !GetAtt OutTonightFunctionRole.Arn
